config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # Temporarily comment this out until Devise is properly installed
  # devise_for :users
  
  root 'home#index'

  get 'about', to: 'about#index'
  get 'books', to: 'books#show_all'
  get 'magazines', to: 'magazines#show_all'
  get 'login', to: 'sessions#new'
  resources :authors, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :publishers, only: [:index, :show]

  resources :books, only: [:show] do
    resources :reviews, only: [:create]
    resources :magazines, only: [:show], controller: 'books/magazines'
  end

  resources :magazines, only: [:show]

  # Routes for showing the search
  resources :books do
    collection do
      get 'show_all' 
    end
  end

  resources :magazines do
    collection do
      get 'show_all' 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_and_belongs_to_many :books
  end
  

app/models/book.rb
class Book < ApplicationRecord
    # Associations
    has_many :magazines
    has_and_belongs_to_many :authors
    belongs_to :category
    has_many :reviews
    belongs_to :publisher, optional: true
    # Validations
    validates :title, presence: true
    validates :authors, presence: true
    validates :published_date, presence: true
    validates :publisher, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
    
  end
  

app/models/magazine.rb
class Magazine < ApplicationRecord
    # Associations
    belongs_to :book
    has_many :reviews, dependent: :destroy
    # Validations
    validates :title, presence: true
    validates :author, presence: true
    validates :published_date, presence: true
    validates :publisher, presence: true
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :books
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book 
  belongs_to :user
  validates :rating, presence: true, inclusion: { in: 1..5 }
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
        @data_sources = [
          { name: 'Books CSV', description: 'CSV file containing book data.' },
          { name: 'Faker Gem', description: 'Gem used to generate fake data for magazines.' }
        ]
      end
end

app/controllers/author_controller.rb
class AuthorsController < ApplicationController
    def index
      @authors = Author.all
    end
  
    def show
      @author = Author.find(params[:id])
    end
  end
  

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def index
      @authors = Author.all
    end
  
    def show
      @author = Author.find(params[:id])
    end
  end
  

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:query].present?
      @books = Book.where("title ILIKE ?", "%#{params[:query]}%").includes(:magazines).page(params[:page]).per(10)
    else
      @books = Book.includes(:magazines).page(params[:page]).per(10)
    end
  end

  def show
    @book = Book.find(params[:id])
    @publisher = @book.publisher
    @reviews = @book.reviews
    @category = @book.category
    @magazines = @book.magazines
  end

  def show_all
    if params[:query].present?
      @books = Book.where("title ILIKE ?", "%#{params[:query]}%").page(params[:page]).per(10)
    else
      @books = Book.all.page(params[:page]).per(10)
    end
    Rails.logger.debug("Total Pages: #{@books.total_pages}")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # def index
  #   @books_with_magazines = Book.includes(:magazines).all
  # end
  # def index
  #   @books_with_magazines = Book.includes(:magazines).page(params[:page]).per(10)
  # end
  # def index
  #   if params[:search].present?
  #     @books_with_magazines = Book.includes(:magazines).where("title LIKE ?", "%#{params[:search]}%").page(params[:page]).per(10)
  #   else
  #     @books_with_magazines = Book.includes(:magazines).page(params[:page]).per(10)
  #   end
  # end
  # Adding display message
  # def index
  #   if params[:search].present?
  #     @books_with_magazines = Book.includes(:magazines).where("title LIKE ?", "%#{params[:search]}%").page(params[:page]).per(10)
  #     if @books_with_magazines.empty?
  #       flash.now[:notice] = "Sorry, no results found."
  #     end
  #   else
  #     @books_with_magazines = Book.includes(:magazines).page(params[:page]).per(10)
  #   end
  # end
  # Adding heirahical search 
  # def index
  #   @books = Book.all
  #   @magazines = Magazine.all

  #   if params[:search].present?
  #     @books_with_magazines = Book.includes(:magazines).where("title LIKE ?", "%#{params[:search]}%").page(params[:page]).per(10)
  #     if @books_with_magazines.empty?
  #       flash.now[:notice] = "Sorry, no results found."
  #     end
  #   else
  #     @books_with_magazines = Book.includes(:magazines).page(params[:page]).per(10)
  #   end
  # end
  def index
    @magazines = Magazine.all
    @books_with_magazines = Book.includes(:magazines)

    if params[:search].present?
      @books_with_magazines = @books_with_magazines.where("books.title ILIKE ?", "%#{params[:search]}%")
    end

    if params[:magazine_id].present?
      @books_with_magazines = @books_with_magazines.joins(:magazines).where(magazines: { id: params[:magazine_id] }).distinct
    end

    if @books_with_magazines.empty?
      flash.now[:notice] = "Sorry, no results found."
    end

    @books_with_magazines = @books_with_magazines.page(params[:page]).per(10)
  end
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  def show_all
    if params[:search].present?
      @magazines = Magazine.where("title LIKE ?", "%#{params[:search]}%").page(params[:page]).per(20)
      if @magazines.empty?
        flash.now[:notice] = "Sorry, no results found."
      end
    else
      @magazines = Magazine.page(params[:page]).per(20)
    end
  end
  def show
    @magazine = Magazine.find(params[:id])
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
    def show
      @publisher = Publisher.find(params[:id])
      @books = @publisher.books # Fetch all books by the publisher
    end
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :check_if_logged_in, only: [:create]

  def check_if_logged_in
    redirect_to login_path unless current_user
  end

  def create
    @book = Book.find(params[:book_id])
    @review = @book.reviews.build(review_params)
    @review.user = current_user  # Assign the current user to the review
    
    if @review.save
      redirect_to @book, notice: 'Review was successfully created.'
    else
      redirect_to @book, alert: 'There was an issue with your review.'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # Render the login form (e.g., 'login.html.erb')
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])  # Assuming you're using has_secure_password
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully."
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out successfully."
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/authors/index.html.erb
<h1>Authors</h1>
<ul>
  <% @authors.each do |author| %>
    <li><%= link_to author.name, author_path(author) %></li>
  <% end %>
</ul>

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>
<p><%= @author.bio %></p>
<%= link_to 'Back to Authors', authors_path %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<p><strong>Authors:</strong> <%= @book.authors.map(&:name).join(", ") %></p>
<p><strong>Published Date:</strong> <%= @book.published_date %></p>
<p><strong>Publisher:</strong> <%= @book.publisher&.name || "No Publisher" %></p>

<h2>Magazines</h2>
<ul>
  <% @book.magazines.each do |magazine| %>
    <li><%= link_to magazine.title, magazine_path(magazine) %></li>
  <% end %>
</ul>

<h2>Reviews</h2>
<%= form_with(model: [ @book, @book.reviews.build ], local: true) do |form| %>
  <div class="form-group">
    <%= form.label :rating, "Rating (1-5)" %>
    <%= form.number_field :rating, min: 1, max: 5, required: true %>
  </div>

  <div class="form-group">
    <%= form.label :comment, "Comment" %>
    <%= form.text_area :comment, required: true, rows: 3 %>
  </div>

  <%= form.submit "Add Review", class: "btn btn-primary" %>
<% end %>

<h3>Existing Reviews</h3>
<ul>
  <% @book.reviews.each do |review| %>
    <li>
      <strong>Rating:</strong> <%= review.rating %><br>
      <strong>Comment:</strong> <%= review.comment %>
    </li>
  <% end %>
</ul>

<%= link_to 'Back to Books', root_path %>

app/views/books/show_all.html.erb
<h1>Books</h1>

<%= form_with(url: books_path, method: "get", local: true) do %>
  <%= text_field_tag :query, params[:query], placeholder: "Search books by title" %>
  <%= submit_tag "Search" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Authors</th>
      <th>Published Date</th>
    </tr>
  </thead>
  <tbody>
  <% if @books.present? %>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book_path(book) %></td>
        <td>
          <% book.authors.each do |author| %>
            <%= author.name %><br> <!-- Display each author's name -->
          <% end %>
        </td>
        <td><%= book.published_date %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="3">No books available</td>
    </tr>
  <% end %>
</tbody>
</table>

<%= paginate @books %> 

app/views/magazines/show.html.erb
<h1><%= @magazine.title %></h1>
<p><strong>Author:</strong> <%= @magazine.author %></p>
<p><strong>Published Date:</strong> <%= @magazine.published_date %></p>
<p><strong>Publisher:</strong> <%= @magazine.publisher %></p>

<p>
  <%= link_to 'Back to Book Details', book_path(@magazine.book) %>
</p>

app/views/magazines/show_all.html.erb
<h1>All Magazines</h1>

<%= form_with(url: magazines_path, method: "get") do %>
  <%= text_field_tag(:search, params[:search], placeholder: "Search for magazines") %>
  <%= submit_tag("Search") %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Published Date</th>
      <th>Publisher</th>
    </tr>
  </thead>
  <tbody>
    <% @magazines.each do |magazine| %>
      <tr>
        <td><%= link_to magazine.title, magazine_path(magazine) %></td>
        <td><%= magazine.author %></td>
        <td><%= magazine.published_date %></td>
        <td><%= magazine.publisher %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if flash[:notice] %>
  <div class="alert alert-warning">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= paginate @magazines %>